IMAGE:
  WIDTH: 640
  HEIGHT: 480
  ROI_START_HEIGHT: 355
  ROI_HEIGHT: 58

XYCAR:
  START_SPEED: 3.0
  MAX_SPEED: 28.0
  MIN_SPEED: 14.0
  SPEED_CONTROL_THRESHOLD: 10
  ACCELERATION_STEP: 0.07
  DECELERATION_STEP: 0.1

PID:
  P_GAIN: 0.43
  
  I_GAIN: 0.000001
  D_GAIN: 0.88

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 30

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

CANNY:
  LOW_THRESHOLD: 200
  HIGH_THRESHOLD: 300

HOUGH:
  ABS_SLOPE_RANGE: 10.0
  THRESHOLD: 20
  MIN_LINE_LENGTH: 25
  MAX_LINE_GAP: 10

DEBUG: true
